# Generated by Django 5.0.6 on 2026-02-10
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        # User model
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("is_superuser", models.BooleanField(default=False, help_text="Designates that this user has all permissions without explicitly asloging them.", verbose_name="superuser status")),
                ("username", models.CharField(
                    error_messages={"unique": "A user with that username already exists."},
                    help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                    max_length=150,
                    unique=True,
                    validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                    verbose_name="username"
                )),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                ("is_staff", models.BooleanField(default=False, help_text="Designates whether the user can log into this admin site.", verbose_name="staff status")),
                ("is_active", models.BooleanField(default=True, help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.", verbose_name="active")),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("first_name", models.CharField(default="", max_length=255)),
                ("last_name", models.CharField(default="", max_length=255)),
                ("phonenumber", models.CharField(blank=True, max_length=255, null=True)),
                ("is_learner", models.BooleanField(default=False)),
                ("is_instructor", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("avatar", models.ImageField(blank=True, default="media/lufy.png", upload_to="media/")),
                ("last_announcements_check", models.DateTimeField(default=django.utils.timezone.now)),
                ("groups", models.ManyToManyField(
                    blank=True,
                    help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                    related_name="user_set",
                    related_query_name="user",
                    to="auth.group",
                    verbose_name="groups"
                )),
                ("user_permissions", models.ManyToManyField(
                    blank=True,
                    help_text="Specific permissions for this user.",
                    related_name="user_set",
                    related_query_name="user",
                    to="auth.permission",
                    verbose_name="user permissions"
                )),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[("objects", django.contrib.auth.models.UserManager())],
        ),

        # Course
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("color", models.CharField(default="#007bff", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),

        # Learner
        migrations.CreateModel(
            name="Learner",
            fields=[
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),

        # Instructor
        migrations.CreateModel(
            name="Instructor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

        # Announcement
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                ("posted_at", models.DateTimeField(auto_now=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

        # Notes
        migrations.CreateModel(
            name="Notes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=500)),
                ("file", models.FileField(blank=True, null=True, upload_to="media/")),
                ("cover", models.ImageField(blank=True, null=True, upload_to="media/")),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.course")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

        # Tutorial
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("thumb", models.ImageField(blank=True, null=True, upload_to="media/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("video", embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ("course", models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, to="learning.course")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

        # Quiz
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quizzes", to="learning.course")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quizzes", to=settings.AUTH_USER_MODEL)),
            ],
        ),

        # Question
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=255, verbose_name="Question")),
                ("quiz", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="learning.quiz")),
            ],
        ),

        # Answer
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=255, verbose_name="Answer")),
                ("is_correct", models.BooleanField(default=False, verbose_name="Correct answer")),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="learning.question")),
            ],
        ),

        # TakenQuiz
        migrations.CreateModel(
            name="TakenQuiz",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.FloatField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("quiz", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="taken_quizzes", to="learning.quiz")),
                ("learner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="taken_quizzes", to="learning.learner")),
            ],
        ),

        # LearnerAnswer
        migrations.CreateModel(
            name="LearnerAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("answer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="learning.answer")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quiz_answers", to="learning.learner")),
            ],
        ),

        # Many-to-many relationships
        migrations.AddField(
            model_name="learner",
            name="interests",
            field=models.ManyToManyField(related_name="interested_learners", to="learning.course"),
        ),
        migrations.AddField(
            model_name="learner",
            name="quizzes",
            field=models.ManyToManyField(through="learning.TakenQuiz", to="learning.quiz"),
        ),
        migrations.AddField(
            model_name="instructor",
            name="interest",
            field=models.ManyToManyField(related_name="more_locations", to="learning.course"),
        ),
    ]